import React, { useState, useCallback } from 'react'
import { timeAgo } from '../hooks/useFeeds.js'
import { SECTION_CATS, OPP_KEYWORDS } from '../config/feeds.js'

function buildPlainText(pool) {
  const now = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })
  const sections = [
    { label: 'ENTERPRISE RISK MANAGEMENT', cats: SECTION_CATS.erm },
    { label: 'FINANCIAL RISK MANAGEMENT',  cats: SECTION_CATS.frm },
    { label: 'REGULATORY & COMPLIANCE',    cats: SECTION_CATS.reg },
    { label: 'MARKET & MACRO TRENDS',      cats: SECTION_CATS.macro },
  ]
  let txt = `RISKHUB360 — RISK INTELLIGENCE DIGEST\n${now}\n${'─'.repeat(50)}\n\n`
  sections.forEach(sec => {
    const seen = new Set()
    const items = pool.filter(a => {
      if (seen.has(a.title) || !sec.cats.includes(a.cat)) return false
      seen.add(a.title); return true
    }).slice(0, 3)
    if (!items.length) return
    txt += `${sec.label}\n${'─'.repeat(30)}\n`
    items.forEach((a, i) => {
      txt += `${i + 1}. ${a.title}\n   ${a.source}${a.date ? ' · ' + timeAgo(a.date) : ''}\n`
      if (a.desc) txt += `   ${a.desc}…\n`
      txt += `   ${a.link}\n\n`
    })
  })
  txt += `\n${'─'.repeat(50)}\nGenerated by RiskHub360`
  return txt
}

export default function EmailDigest({ pool, isOpen, onClose }) {
  const [recipient, setRecipient] = useState('')
  const [copied, setCopied]       = useState(false)

  const now = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })

  const sendEmail = useCallback(() => {
    const subject = encodeURIComponent(`RiskHub360 Daily Digest — ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`)
    const body    = encodeURIComponent(buildPlainText(pool))
    window.location.href = `mailto:${recipient}?subject=${subject}&body=${body}`
  }, [pool, recipient])

  const copyText = useCallback(() => {
    navigator.clipboard.writeText(buildPlainText(pool)).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }, [pool])

  if (!isOpen) return null

  // Build preview sections
  const sections = [
    { label: 'Enterprise Risk Management', cats: SECTION_CATS.erm },
    { label: 'Financial Risk Management',  cats: SECTION_CATS.frm },
    { label: 'Regulatory & Compliance',    cats: SECTION_CATS.reg },
    { label: 'Market & Macro Trends',      cats: SECTION_CATS.macro },
  ]

  return (
    <div
      style={{
        position: 'fixed', inset: 0,
        background: 'rgba(0,43,91,.55)',
        zIndex: 1000, display: 'flex', alignItems: 'center', justifyContent: 'center',
        padding: 20, backdropFilter: 'blur(3px)',
        animation: 'fadeUp .2s ease',
      }}
      onClick={e => e.target === e.currentTarget && onClose()}
    >
      <div style={{
        background: 'var(--card)', border: '1px solid var(--border2)',
        borderRadius: 12, width: '100%', maxWidth: 680,
        maxHeight: '88vh', display: 'flex', flexDirection: 'column',
        boxShadow: '0 20px 60px rgba(0,43,91,.2)',
      }}>
        {/* Header */}
        <div style={{ padding: '20px 24px 16px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexShrink: 0 }}>
          <div>
            <div style={{ fontSize: 16, fontWeight: 700, color: 'var(--orange)' }}>📧 RiskHub360 Daily Digest</div>
            <div style={{ fontSize: 11.5, color: 'var(--txt3)', marginTop: 3 }}>Top articles from all feeds · {now}</div>
          </div>
          <button onClick={onClose} style={{ width: 30, height: 30, background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 6, color: 'var(--txt3)', fontSize: 16, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>✕</button>
        </div>

        {/* Preview */}
        <div style={{ padding: '20px 24px', overflowY: 'auto', flex: 1 }}>
          <div style={{ background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 8, padding: 20, fontSize: 12.5, lineHeight: 1.7, color: 'var(--txt2)' }}>
            {/* Digest header */}
            <div style={{ borderBottom: '2px solid var(--navy)', paddingBottom: 14, marginBottom: 18 }}>
              <div style={{ fontSize: 18, fontWeight: 800, color: 'var(--orange)' }}>RiskHub<span style={{ color: 'var(--orange)' }}>360</span></div>
              <div style={{ fontSize: 11, color: 'var(--txt3)', marginTop: 4 }}>{now}</div>
            </div>

            {sections.map(sec => {
              const seen = new Set()
              const items = pool.filter(a => {
                if (seen.has(a.title) || !sec.cats.includes(a.cat)) return false
                seen.add(a.title); return true
              }).slice(0, 3)
              if (!items.length) return null
              return (
                <div key={sec.label} style={{ marginBottom: 18 }}>
                  <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: 2, textTransform: 'uppercase', color: 'var(--orange)', marginBottom: 10, paddingBottom: 6, borderBottom: '1px solid var(--border)' }}>
                    {sec.label}
                  </div>
                  {items.map((a, i) => (
                    <div key={i} style={{ padding: '9px 0', borderBottom: i < items.length - 1 ? '1px solid var(--border)' : 'none' }}>
                      <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--txt)', lineHeight: 1.4, marginBottom: 3 }}>{a.title}</div>
                      <div style={{ fontSize: 10.5, color: 'var(--txt3)' }}>{a.source}{a.date ? ' · ' + timeAgo(a.date) : ''} · <a href={a.link} target="_blank" rel="noopener noreferrer" style={{ color: 'var(--orange)' }}>Read →</a></div>
                      {a.desc && <div style={{ fontSize: 11.5, color: 'var(--txt2)', marginTop: 3, lineHeight: 1.55 }}>{a.desc}…</div>}
                    </div>
                  ))}
                </div>
              )
            })}

            <div style={{ marginTop: 16, paddingTop: 12, borderTop: '1px solid var(--border)', fontSize: 10.5, color: 'var(--txt3)', textAlign: 'center' }}>
              Generated by RiskHub360
            </div>
          </div>
        </div>

        {/* Footer actions */}
        <div style={{ padding: '16px 24px', borderTop: '1px solid var(--border)', display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0, flexWrap: 'wrap' }}>
          <span style={{ fontSize: 11, fontWeight: 600, color: 'var(--txt3)', whiteSpace: 'nowrap' }}>To:</span>
          <input
            type="email"
            value={recipient}
            onChange={e => setRecipient(e.target.value)}
            placeholder="recipient@company.com"
            style={{ flex: 1, minWidth: 180, background: 'var(--bg)', border: '1.5px solid var(--border)', borderRadius: 7, padding: '8px 12px', fontFamily: 'var(--font)', fontSize: 12.5, color: 'var(--txt)', outline: 'none' }}
            onFocus={e => e.target.style.borderColor = 'var(--navy2)'}
            onBlur={e  => e.target.style.borderColor = 'var(--border)'}
          />
          <button onClick={copyText} style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--bg)', color: copied ? 'var(--green)' : 'var(--txt2)', border: '1px solid var(--border)', padding: '9px 16px', borderRadius: 7, fontFamily: 'var(--font)', fontWeight: 600, fontSize: 12, cursor: 'pointer', whiteSpace: 'nowrap' }}>
            {copied ? '✅ Copied!' : '📋 Copy'}
          </button>
          <button onClick={sendEmail} style={{ display: 'flex', alignItems: 'center', gap: 7, background: 'var(--orange)', color: '#fff', border: 'none', padding: '9px 20px', borderRadius: 7, fontFamily: 'var(--font)', fontWeight: 700, fontSize: 12.5, cursor: 'pointer', whiteSpace: 'nowrap' }}>
            📤 Open in Mail App
          </button>
        </div>
      </div>
    </div>
  )
}
